### ISSUE TITLE
[MPLUGINTESTING-57] plugin.xml is needed

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-testing#179]
**[Gerrit Hohl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=g.hohl)** opened **[MPLUGINTESTING-57](https://issues.apache.org/jira/browse/MPLUGINTESTING-57?redirect=false)** and commented

For the test being executable the plugin.xml created by the maven-plugin-plugin is needed. But this plugin only runs during the build time of the Maven project of your plugin. If I use e.g. Eclipse and JUnit I don't have this file. But I guess it should be possible to get all the needed information also during runtime of the test as the maven-plugin-plugin also doesn't have any extra sources beside the Mojo and its annotations.

---

**Affects:** 3.3.0

**Issue Links:**
- [MPLUGIN-351](https://issues.apache.org/jira/browse/MPLUGIN-351) Support m2e execution of goal "descriptor"

0 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin)** commented

I created MPLUGIN-351 for supporting the m2e execution of goal "descriptor".

**Comment by jira-importer** [comment]
**[Antony Stubbs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=astubbs)** commented

The maven plugin archetype also appears to produce a test which cannot run, due to this error:

 

`junit.framework.AssertionFailedError: The MojoDescriptor for the goal touch cannot be null.`
`at junit.framework.Assert.fail(Assert.java:57) at junit.framework.Assert.assertTrue(Assert.java:22) at junit.framework.Assert.assertNotNull(Assert.java:256) at junit.framework.TestCase.assertNotNull(TestCase.java:426) at org.apache.maven.plugin.testing.AbstractMojoTestCase.newMojoExecution(AbstractMojoTestCase.java:515) at org.apache.maven.plugin.testing.MojoRule.newMojoExecution(MojoRule.java:207) at org.apache.maven.plugin.testing.MojoRule.lookupConfiguredMojo(MojoRule.java:354) at `

**Comment by slawekjaranowski** [comment]
linked issues was resolved, so I hope we can close it
